### ISSUE TITLE
/Points where on users not in guild

### ISSUE THREAD

**Issue by solumath** [GrillBot/grillbot#27]
when using /points where on user that is not guild returns error and also the bot writes error to user's DM
![image](https://user-images.githubusercontent.com/56552845/213260822-a47a3143-d3e3-4c41-8cf2-f001f9f8a3e6.png)

**Comment by Misha12** [comment]
1) `/points where` where user is not in the guild was fixed in the https://github.com/GrillBot/grillbot/commit/9e7b97344b6b53fdb1c6c0c837324be2dae375bf but wasn't deployed latest container in the production.
2) Bug where bot sent an error message to the DM and as response is investigating, but probably is slow rendering of WithoutAccident image cause chaotic ThreadPool task processing in the Discord.NET library.
