### ISSUE TITLE
Names out of picture

### ISSUE THREAD

**Issue by solumath** [GrillBot/grillbot#82]
When calling `/points where` the image generated is trying to fit all names user has (display name, global name, server nickname) 
![image](https://github.com/GrillBot/grillbot/assets/56552845/b3297240-7033-40e8-9230-4885025ac401)
I dont think that's needed as the user himself is calling it so we know exactly who he is. Only Global name could be enough.
Can be discussed

**Comment by Misha12** [comment]
I think it will be enough to show only one display name, not all of them. If the user has a guild nickname, show the nickname, otherwise show the global name and the username will be displayed if the user has neither a nickname nor a global name. How discord presents the names of users in the channel.
